

<div class="digiBody">
    <div class="header">
        <h1>La Digi Checklist</h1>
    </div>


    <div class="body">
        <?php foreach($this->todos as $todo) :?>
            <div class="item" id="item_<?=$todo['id_todo']?>" ><div class="checkContainer"><div class="check" id="<?=$todo["id_todo"]?>"></div></div><div class="todo"><p><?=$todo["todo"]?></p></div></div>
        <?php endforeach?>
    </div>
</div>


<div class="containerAdd">

    <div class="headerAdd"><h1>Ajoute ta digiActivité !</h1></div>

    <div class=bodyAdd>
        <input placeholder="Ma DigiActivité" class="input" type="text">
    </div>

    <div class="footerAdd"> <button>Ajouter!</button> </div>
    
</div>

<div class="add"><p class="plus">+</p></div>
<link rel="stylesheet" href="<?=Zend_Controller_Front::getInstance()->getBaseUrl() ?>/style/style.css">

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

<script src="<?=Zend_Controller_Front::getInstance()->getBaseUrl() ?>/js/app.js"></script>